### ISSUE TITLE
Error in def get_dataset

### ISSUE THREAD

**Issue by natandrade** [96imranahmed/3D-Unet#1]
Hello,

I am getting the following error:

![image](https://user-images.githubusercontent.com/24567632/57576682-7cabbb80-743c-11e9-8ff4-98b94eb4e3c7.png)

The directory of each type seems to be correct. And they are being recognized by the code.

I believe there may be an error in trying to figure out the amount of .dcm for each patient, since len (d_dcm [i]) gives error.

So I would like your help in this mistake!

Thanks in advance!

**Comment by 96imranahmed** [comment]
Hey, so what this is saying is that you have annotations for `Prostate3T-01-0001` but don't have an associated raw-file in your data directory. 

I'm not too sure how to resolve this - can you verify that all these files are available in the respective directories? A hot-fix would be to just delete the `Prostate3T-01-0001` nrrd file from your labels directory!

**Comment by natandrade** [comment]
Thanks for the answer! :)

Answering your question

I have both types of files (nrrd and dcm)!

The directory of both images is organized the way you download the images from the link (https://wiki.cancerimagingarchive.net/display/Public/NCI-ISBI+2013+Challenge+-+Automated+Segmentation+of+Prostate+Structures).

For .dcm
\ 3D-Unet-master \ data \ train \ Prostate-3T \ Prostate3T-01-0001 \ 1.3.6.1.4.1.14519.5.2.1.7308.2101.878027069026309930088081179232 \ 1.3.6.1.4.1.14519.5.2.1.7308.2101.294123309272114469889813649698 \

000000.dcm
000001.dcm
000002.dcm
.
.
.

For the nrrd
\ 3D-Unet-master \ data \ train-segm \

Prostate3T-01-0001.nrrd
Prostate3T-01-0002.nrrd
Prostate3T-01-0003.nrrd
.
.
.

From what I understand the error is in the for loop, since it does not run through a dictionary with indices

Thanks in advance!
